<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <Deterministic>true</Deterministic>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Label="Package Versions">
    <EntityFrameworkCoreVersion>9.0.5</EntityFrameworkCoreVersion>
    <MicrosoftExtensionsVersion>9.0.4</MicrosoftExtensionsVersion>
    <NewtonsoftVersion>13.0.3</NewtonsoftVersion>
  </PropertyGroup>

  <ItemGroup Label="Common Package References">
    <PackageReference Update="Microsoft.EntityFrameworkCore" Version="$(EntityFrameworkCoreVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Design" Version="$(EntityFrameworkCoreVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkCoreVersion)" />
    <PackageReference Update="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Microsoft.Extensions.Configuration.Json" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Microsoft.Extensions.Configuration.FileExtensions" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Newtonsoft.Json" Version="$(NewtonsoftVersion)" />
  </ItemGroup>
</Project>