services:
  proxy-manager:
    build:
      dockerfile: ./proxy-manager/Dockerfile #todo: context
    volumes:
      - /var/lib/rwparcer-dev/proxies.txt:/app/proxies.txt:ro
    environment:
      PROXY_MANAGER_PORT: 8080
      HEALTH_CHECK_INTERVAL: 30
    restart: unless-stopped


  parcer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/rwparcer-dev/data:/app/data
    restart: unless-stopped
    environment:
      APPSETTINGS_JSON: ${APPSETTINGS_JSON}
      PROXY_MANAGER_URL: ${PROXY_MANAGER_URL:-http://proxy-manager:8080}
