services:
  parcer:
    build:
      context: .
      dockerfile: Dockerfile
    image: rwparcer-local
    container_name: rwparcer-app
    volumes:
      - /etc/secrets/appsettings.json:/etc/secrets/appsettings.json:ro
    restart: always