services:
  psiphon:
    image: ghcr.io/danilaltd/rwparcer-psiphon:dev-latest
    volumes:
      - /var/lib/rwparcer-dev/data:/app/data
    environment:
      NODE_ID_FROM_HOSTNAME: "1"
    deploy:
      replicas: 2
    restart: always


  parcer:
    image: ghcr.io/danilaltd/rwparcer:dev-latest
    volumes:
      - ./env/appsettings.json:/etc/secrets/appsettings.json:ro
      - /var/lib/rwparcer-dev/data:/app/data
    restart: unless-stopped
    environment:
      PSIPHON_REPLICAS: 2
