services:
  parcer:
    build: .
    image: rwparcer-local
    container_name: rwparcer-app
    volumes:
      - ./env/appsettings.json:/etc/secrets/appsettings.json:ro
      - ./env/data:/app/data
    restart: unless-stopped