services:
  parcer:
    build: .
    image: rwparcer-local
    container_name: rwparcer-app
    volumes:
      - ./env/appsettings.json:/etc/secrets/appsettings.json:ro
      - ./env/index.state:/app/data/index.state
    restart: unless-stopped