"""Protocol (interface) definitions for the normalized schema."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    import datetime
    import uuid

    from app.domain.entities import Favorite, Message, Notification, Subscription, User
    from app.domain.value_objects import Car, Route, Station, SubscriptionDetails, Train


@runtime_checkable
class Logger(Protocol):
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...


@runtime_checkable
class UserRepository(Protocol):
    async def register_user(self, telegram_user_id: int, telegram_chat_id: int) -> User: ...
    async def is_user_registered(self, user_id: uuid.UUID) -> bool: ...
    async def add_user(self, user: User) -> None: ...
    async def get_user_min_interval(self, user_id: uuid.UUID) -> int: ...
    async def is_user_moderator(self, user_id: uuid.UUID) -> bool: ...
    async def get_user_max_subscriptions(self, user_id: uuid.UUID) -> int: ...
    async def get_user_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def set_users_min_interval(self, user_id: uuid.UUID, min_interval: int) -> None: ...
    async def set_users_max_subscriptions(
        self, user_id: uuid.UUID, max_subscriptions: int
    ) -> None: ...
    async def ban_user(self, user_id: uuid.UUID) -> None: ...
    async def unban_user(self, user_id: uuid.UUID) -> None: ...
    async def promote_user(self, user_id: uuid.UUID) -> None: ...
    async def demote_user(self, user_id: uuid.UUID) -> None: ...
    async def is_user_banned(self, user_id: uuid.UUID) -> bool: ...
    async def update_activity(self, user_id: uuid.UUID) -> None: ...
    async def get_last_users(self, time_span: datetime.timedelta) -> list[User]: ...
    async def get_moderators(self) -> list[User]: ...


@runtime_checkable
class TransportRepository(Protocol):
    async def get_or_create_service_route(self, details: SubscriptionDetails) -> uuid.UUID: ...


@runtime_checkable
class SubscriptionRepository(Protocol):
    async def get_user_subscriptions(self, user_id: uuid.UUID) -> list[Subscription]: ...
    async def get_all_subscriptions(self) -> list[Subscription]: ...
    async def get_by_id(self, subscription_id: uuid.UUID) -> Subscription | None: ...
    async def add_subscription(self, subscription: Subscription) -> None: ...
    async def remove_subscription(self, subscription: Subscription) -> None: ...
    async def subscription_exists(
        self, user_id: uuid.UUID, service_route_id: uuid.UUID, target_date: datetime.date
    ) -> bool: ...
    async def get_subscription_count(self, user_id: uuid.UUID) -> int: ...
    async def update_subscription(self, subscription: Subscription) -> None: ...
    async def reset_subscription(self, subscription: Subscription) -> None: ...
    async def claim_due_subscriptions(self, limit: int = 10) -> list[Subscription]: ...
    async def save_availability_snapshot(
        self, subscription_id: uuid.UUID, cars: list[Car]
    ) -> bool: ...


@runtime_checkable
class FavoritesRepository(Protocol):
    async def get_favorites(self, user_id: uuid.UUID) -> list[Favorite]: ...
    async def add_favorite(self, favorite: Favorite) -> None: ...
    async def remove_favorite(self, favorite: Favorite) -> None: ...
    async def favorite_exists(self, user_id: uuid.UUID, service_route_id: uuid.UUID) -> bool: ...


@runtime_checkable
class NotificationRepository(Protocol):
    async def claim_pending_notifications(self, limit: int = 50) -> list[Notification]: ...
    async def mark_sent(self, notification_id: uuid.UUID) -> None: ...
    async def mark_failed(self, notification_id: uuid.UUID, error_text: str) -> None: ...
    async def add_notification(self, notification: Notification) -> None: ...


@runtime_checkable
class MessageRepository(Protocol):
    async def add_message(self, message: Message) -> None: ...
    async def get_user_messages(self, user_id: uuid.UUID) -> list[Message]: ...
    async def get_all_messages(self) -> list[Message]: ...


@runtime_checkable
class RwRepository(Protocol):
    async def get_stations(self, prefix: str) -> list[Station]: ...
    async def get_trains(self, route: Route) -> list[Train]: ...
    async def get_seats(self, details: SubscriptionDetails) -> list[Car]: ...
