"""Protocol (interface) definitions for the normalized schema."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    import datetime
    import uuid

    from app.domain.entities import Favorite, Message, Notification, Subscription, User
    from app.domain.value_objects import Car, Route, Station, SubscriptionDetails, Train


@runtime_checkable
class Logger(Protocol):
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------


@runtime_checkable
class RoleRepository(Protocol):
    async def get_role_id(self, role_code: str) -> int | None: ...
    async def ensure_default_roles(self) -> None: ...


@runtime_checkable
class UserRoleRepository(Protocol):
    async def has_role(self, user_id: uuid.UUID, role_code: str) -> bool: ...
    async def grant_role(self, user_id: uuid.UUID, role_code: str) -> None: ...
    async def revoke_role(self, user_id: uuid.UUID, role_code: str) -> None: ...
    async def get_user_ids_with_role(self, role_code: str) -> list[uuid.UUID]: ...


@runtime_checkable
class UserRepository(Protocol):
    async def register_user(
        self, telegram_user_id: int, telegram_chat_id: int, username: str | None, display_name: str
    ) -> User: ...
    async def is_user_registered(self, user_id: uuid.UUID) -> bool: ...
    async def add_user(self, user: User) -> None: ...
    async def get_user_min_interval(self, user_id: uuid.UUID) -> int: ...
    async def is_user_moderator(self, user_id: uuid.UUID) -> bool: ...
    async def get_user_max_subscriptions(self, user_id: uuid.UUID) -> int: ...
    async def get_user_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def set_users_min_interval(self, user_id: uuid.UUID, min_interval: int) -> None: ...
    async def set_users_max_subscriptions(
        self, user_id: uuid.UUID, max_subscriptions: int
    ) -> None: ...
    async def ban_user(self, user_id: uuid.UUID) -> None: ...
    async def unban_user(self, user_id: uuid.UUID) -> None: ...
    async def promote_user(self, user_id: uuid.UUID) -> None: ...
    async def demote_user(self, user_id: uuid.UUID) -> None: ...
    async def is_user_banned(self, user_id: uuid.UUID) -> bool: ...
    async def update_activity(self, user_id: uuid.UUID) -> None: ...
    async def get_last_users(self, time_span: datetime.timedelta) -> list[User]: ...
    async def get_moderators(self) -> list[User]: ...


# ---------------------------------------------------------------------------
# Transport catalog
# ---------------------------------------------------------------------------


@runtime_checkable
class ServiceRouteRepository(Protocol):
    async def get_or_create_service_route(self, details: SubscriptionDetails) -> uuid.UUID: ...
    async def get_train(self, service_route_id: uuid.UUID) -> Train | None: ...


# ---------------------------------------------------------------------------
# Monitoring
# ---------------------------------------------------------------------------


@runtime_checkable
class SubscriptionRepository(Protocol):
    async def get_user_subscriptions(self, user_id: uuid.UUID) -> list[Subscription]: ...
    async def get_all_subscriptions(self) -> list[Subscription]: ...
    async def get_by_id(self, subscription_id: uuid.UUID) -> Subscription | None: ...
    async def add_subscription(self, subscription: Subscription) -> None: ...
    async def remove_subscription(self, subscription: Subscription) -> None: ...
    async def subscription_exists(
        self, user_id: uuid.UUID, service_route_id: uuid.UUID, target_date: datetime.date
    ) -> bool: ...
    async def get_subscription_count(self, user_id: uuid.UUID) -> int: ...
    async def update_subscription(self, subscription: Subscription) -> None: ...
    async def reset_subscription(self, subscription: Subscription) -> None: ...
    async def claim_due_subscriptions(self, limit: int = 10) -> list[Subscription]: ...


@runtime_checkable
class FavoriteRepository(Protocol):
    async def get_favorites(self, user_id: uuid.UUID) -> list[Favorite]: ...
    async def add_favorite(self, favorite: Favorite) -> None: ...
    async def remove_favorite(self, favorite: Favorite) -> None: ...
    async def favorite_exists(self, user_id: uuid.UUID, service_route_id: uuid.UUID) -> bool: ...


@runtime_checkable
class AvailabilitySnapshotRepository(Protocol):
    async def save_snapshot(self, subscription_id: uuid.UUID, cars: list[Car]) -> bool: ...
    async def get_latest_snapshot(self, subscription_id: uuid.UUID) -> list[Car]: ...


# ---------------------------------------------------------------------------
# Messaging
# ---------------------------------------------------------------------------


@runtime_checkable
class NotificationRepository(Protocol):
    async def claim_pending_notifications(self, limit: int = 50) -> list[Notification]: ...
    async def mark_sent(self, notification_id: uuid.UUID) -> None: ...
    async def mark_failed(self, notification_id: uuid.UUID, error_text: str) -> None: ...
    async def add_notification(self, notification: Notification) -> None: ...


@runtime_checkable
class MessageRepository(Protocol):
    async def add_message(self, message: Message) -> None: ...
    async def get_user_messages(self, user_id: uuid.UUID) -> list[Message]: ...
    async def get_all_messages(self) -> list[Message]: ...


# ---------------------------------------------------------------------------
# Bot / audit
# ---------------------------------------------------------------------------


@runtime_checkable
class ConversationSessionRepository(Protocol):
    async def get(self, user_id: uuid.UUID) -> dict[str, Any] | None: ...

    async def save(
        self,
        *,
        user_id: uuid.UUID,
        current_command_code: int | None,
        last_input_date: datetime.date | None,
        init_state: bool,
        context: dict[str, Any],
        expires_at: datetime.datetime | None,
    ) -> None: ...

    async def delete(self, user_id: uuid.UUID) -> None: ...


@runtime_checkable
class AuditLogRepository(Protocol):
    async def add(
        self,
        *,
        actor_user_id: uuid.UUID | None,
        action_code: str,
        entity_schema: str | None = None,
        entity_table: str | None = None,
        entity_id: str | None = None,
        old_values: dict[str, Any] | None = None,
        new_values: dict[str, Any] | None = None,
        correlation_id: uuid.UUID | None = None,
        source: str = "BOT",
    ) -> None: ...


# ---------------------------------------------------------------------------
# External railway provider
# ---------------------------------------------------------------------------


@runtime_checkable
class RwRepository(Protocol):
    async def get_stations(self, prefix: str) -> list[Station]: ...
    async def get_trains(self, route: Route) -> list[Train]: ...
    async def get_seats(self, details: SubscriptionDetails) -> list[Car]: ...
