"""Protocol (interface) definitions, mirroring the C# repository interfaces.

Fakes live only in ``tests/``; these protocols exist so the application layer
depends on abstractions, exactly like the original ``I*Repository`` types.
"""

from __future__ import annotations

import datetime
import uuid
from typing import Protocol, runtime_checkable

from app.domain.entities import Favorite, Message, Notification, Subscription, User
from app.domain.value_objects import Car, Route, Station, SubscriptionDetails, Train


@runtime_checkable
class Logger(Protocol):
    """C# ``ILogger`` (only ``LogDebug`` is used in the hot paths)."""

    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...


@runtime_checkable
class UserRepository(Protocol):
    async def is_user_registered(self, user_id: str) -> bool: ...
    async def add_user(self, user: User) -> None: ...
    async def get_user_min_interval(self, user_id: str) -> int: ...
    async def is_user_moderator(self, user_id: str) -> bool: ...
    async def get_user_max_subscriptions(self, user_id: str) -> int: ...
    async def get_user_by_id(self, user_id: str) -> User | None: ...
    async def set_users_min_interval(self, user_id: str, min_interval: int) -> None: ...
    async def set_users_max_subscriptions(self, user_id: str, max_subscriptions: int) -> None: ...
    async def ban_user(self, user_id: str) -> None: ...
    async def unban_user(self, user_id: str) -> None: ...
    async def promote_user(self, user_id: str) -> None: ...
    async def demote_user(self, user_id: str) -> None: ...
    async def is_user_banned(self, user_id: str) -> bool: ...
    async def update_activity(self, user_id: str) -> None: ...
    async def get_last_users(self, time_span: datetime.timedelta) -> list[User]: ...
    async def get_moderators(self) -> list[User]: ...


@runtime_checkable
class SubscriptionRepository(Protocol):
    async def get_user_subscriptions(self, user_id: str) -> list[Subscription]: ...
    async def get_all_subscriptions(self) -> list[Subscription]: ...
    async def get_by_id(self, subscription_id: uuid.UUID) -> Subscription | None: ...
    async def add_subscription(self, subscription: Subscription) -> None: ...
    async def remove_subscription(self, subscription: Subscription) -> None: ...
    async def subscription_exists(self, user_id: str, details: SubscriptionDetails) -> bool: ...
    async def get_subscription_count(self, user_id: str) -> int: ...
    async def update_subscription(self, subscription: Subscription) -> None: ...
    async def reset_subscription(self, subscription: Subscription) -> None: ...


@runtime_checkable
class FavoritesRepository(Protocol):
    async def get_favorites(self, user_id: str) -> list[Favorite]: ...
    async def add_favorite(self, favorite: Favorite) -> None: ...
    async def remove_favorite(self, favorite: Favorite) -> None: ...
    async def favorite_exists(self, user_id: str, train: Train) -> bool: ...


@runtime_checkable
class NotificationRepository(Protocol):
    async def pop_all(self) -> list[Notification]: ...
    async def add_notification(self, notification: Notification) -> None: ...


@runtime_checkable
class MessageRepository(Protocol):
    async def add_message(self, message: Message) -> None: ...
    async def get_user_messages(self, user_id: str) -> list[Message]: ...
    async def get_all_messages(self) -> list[Message]: ...


@runtime_checkable
class RwRepository(Protocol):
    """C# ``IRWRepository``."""

    async def get_stations(self, prefix: str) -> list[Station]: ...
    async def get_trains(self, route: Route) -> list[Train]: ...
    async def get_seats(self, details: SubscriptionDetails) -> list[Car]: ...
