services:
  postgres:
    image: postgres:18.6
    container_name: transport-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: transport_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: