// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RWParcer.Infrastructure.Database;

#nullable disable

namespace RWParcer.Migrations
{
    [DbContext(typeof(SessionDbContext))]
    partial class SessionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RWParcer.SessionEntity", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentCommand")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("InitState")
                        .HasColumnType("boolean");

                    b.HasKey("ChatId");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
